name: jreleaser

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:

    - id: setup-java
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17

# CREATE A RELEASE
    - id: jreleaser
      name: Run JReleaser
      uses: jreleaser/release-action@v1
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
