name: Other Releases Managed by JReleaser

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '*'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-[A-Z]

jobs:
  release:
    name: Other Releases
    runs-on: ubuntu-latest

    steps:

    - id: setup-java
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: download-distribution
      name: Download distribution
      shell: bash
      run: |
        # Download distribution
        wget -N -q \
        https://github.com/schemacrawler/SchemaCrawler/releases/download/v16.16.10/schemacrawler-16.16.10-distribution.zip
        test -f schemacrawler-16.16.10-distribution.zip && echo "Downloaded distribution"
        ls -ltr

# CREATE A RELEASE
    - id: jreleaser
      name: Run JReleaser
      uses: jreleaser/release-action@v1
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JRELEASER_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        JRELEASER_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        JRELEASER_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        JRELEASER_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        JRELEASER_CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
        JRELEASER_CHOCOLATEY_GITHUB_TOKEN: ${{ secrets.CHOCOLATEY_GITHUB_TOKEN }}
