name: Other Releases Managed by JReleaser

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '*'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-[A-Z]

jobs:
  release:
    name: Other Releases
    runs-on: windows-latest

    steps:

    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: download-distribution
      name: Download distribution
      shell: pwsh
      run: |
        # Download binary distribution
        Invoke-WebRequest -OutFile schemacrawler-16.16.10-bin.zip -Uri  https://github.com/schemacrawler/SchemaCrawler/releases/download/v16.16.10/schemacrawler-16.16.10-bin.zip

# CREATE A RELEASE
    - id: jreleaser
      name: Run JReleaser
      uses: jreleaser/release-action@v2
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JRELEASER_TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        JRELEASER_TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        JRELEASER_TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        JRELEASER_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        JRELEASER_CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
        JRELEASER_CHOCOLATEY_GITHUB_TOKEN: ${{ secrets.CHOCOLATEY_GITHUB_TOKEN }}
        JRELEASER_SDKMAN_CONSUMER_KEY: ${{ secrets.SDKMAN_CONSUMER_KEY }}
        JRELEASER_SDKMAN_CONSUMER_TOKEN: ${{ secrets.SDKMAN_CONSUMER_TOKEN }}
      with:
        version: early-access
        arguments: "full-release -g"
        shell: pwsh
    - id: persist-jreleaser-out
      name: Persist JReleaser out/ directory
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: jreleaser-out
        path: |
          ./out/
        retention-days: 1
