name: Build Installers

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - '*'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-[A-Z]

jobs:

### DOWNLOAD SCHEMACRAWLER DISTRIBUTION
  download-schemacrawler-distribution:
    name: Download SchemaCrawler distribution
    runs-on: ubuntu-latest
    steps:

# Build SchemaCrawler - BUILD FOR DISTRIBUTION
    - id: obtain-distribution
      name: Obtain distribution
      shell: bash
      run: |
        # Obtain distribution
        wget -N -q \
        https://github.com/schemacrawler/SchemaCrawler/releases/download/v16.17.2/schemacrawler-16.17.2-bin.zip
        test -f schemacrawler-16.17.2-bin.zip && echo "Downloaded binary distribution"
        mkdir ./schemacrawler-lib
        mkdir ./schemacrawler-icons
        unzip schemacrawler-16.17.2-bin.zip
        cp \
          ./schemacrawler-16.17.2-bin/lib/* \
          ./schemacrawler-lib/
        cp \
          ./schemacrawler-16.17.2-bin/logos/* \
          ./schemacrawler-icons/
        ls -lR ./schemacrawler-lib/
        ls -lR ./schemacrawler-icons/

# Build SchemaCrawler - SAVE DISTRIBUTION
    - id: upload-distrib-lib
      name: Upload distribution - lib/ folder
      uses: actions/upload-artifact@v2
      with:
        path: ./schemacrawler-lib/
        name: schemacrawler-lib
        retention-days: 1
    - id: upload-distrib-icons
      name: Upload distribution - icons/ folder
      uses: actions/upload-artifact@v2
      with:
        path: ./schemacrawler-icons/
        name: schemacrawler-icons
        retention-days: 1


### BUILD LINUX INSTALLER
  build-linux-installer:
    name: Build Linux Installer
    runs-on: ubuntu-latest
    needs: [download-schemacrawler-distribution]
    steps:

# Build Linux Installer - SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17

# Build Linux Installer - BUILD INSTALLER
    - id: download-distrib-lib
      name: Download distribution
      uses: actions/download-artifact@v2
    - id: build-installer
      name: Build installer
      shell: bash
      run: |
        # Build installer
        mkdir ./schemacrawler-installers
        jpackage --verbose "@jpackage.cfg" "@jpackage-linux.cfg"
        mv \
          ./schemacrawler-installers/schemacrawler_16.17.2-1_amd64.deb \
          ./schemacrawler-installers/schemacrawler-16.17.2.deb
        sha256sum -b \
          ./schemacrawler-installers/schemacrawler-16.17.2.deb \
          > ./schemacrawler-installers/schemacrawler-16.17.2.deb.SHA256
        ls -l ./schemacrawler-installers

# Build Linux Installer - SAVE INSTALLER
    - id: upload-installer
      name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        path: ./schemacrawler-installers/*
        name: linux-installer
        retention-days: 1


### BUILD WINDOWS INSTALLER
  build-windows-installer:
    name: Build Windows Installer
    runs-on: windows-latest
    needs: [download-schemacrawler-distribution]
    steps:

# Build Windows Installer - SETUP BUILD ENVIRONMENT
    - id: checkout-code
      name: Checkout code
      uses: actions/checkout@v2
    - id: setup-jdk
      name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: 17

# Build Windows Installer - BUILD INSTALLER
    - id: download-distrib-lib
      name: Download distribution
      uses: actions/download-artifact@v2
    - id: build-installer
      name: Build installer
      shell: bash
      run: |
        # Build installer
        mkdir ./schemacrawler-installers
        jpackage --verbose "@jpackage.cfg" "@jpackage-windows.cfg"
        sha256sum -b \
          ./schemacrawler-installers/SchemaCrawler-16.17.2.msi \
          > ./schemacrawler-installers/SchemaCrawler-16.17.2.msi.SHA256
        ls -l ./schemacrawler-installers

# Build Windows Installer - SAVE INSTALLER
    - id: upload-installer
      name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        path: ./schemacrawler-installers/*
        name: windows-installer
        retention-days: 1


### CREATE RELEASE
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-linux-installer, build-windows-installer]
    steps:

# Create Release - DOWNLOAD INSTALLERS
    - id: download-linux-installer
      name: Download Linux installer
      uses: actions/download-artifact@v2
      with:
        name: linux-installer
    - id: download-windows-installer
      name: Download Windows installer
      uses: actions/download-artifact@v2
      with:
        name: windows-installer


# Create Release - CREATE GITHUB RELEASE AND ADD ASSETS
    - id: upload-artifacts
      name: Upload installers
      uses: actions/upload-artifact@v2
      with:
        name: all-installers
        path: |
          schemacrawler-16.17.2.deb
          schemacrawler-16.17.2.deb.SHA256
          SchemaCrawler-16.17.2.msi
          SchemaCrawler-16.17.2.msi.SHA256
          schemacrawler.json
        retention-days: 1
    - id: create-release
      name: Create GitHub release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ github.ref_name }}
        draft: false
        prerelease: true
        body: |
          See the change history at https://www.schemacrawler.com/changes-report.html
        generate_release_notes: true
        files: |
          schemacrawler-16.17.2.deb
          schemacrawler-16.17.2.deb.SHA256
          SchemaCrawler-16.17.2.msi
          SchemaCrawler-16.17.2.msi.SHA256

### PUBLISH WINGET PACKAGE
  publish-winget-pkg:
    name: Publish winget package
    needs: [create-release]
    runs-on: windows-latest

    steps:

# Publish winget package - PUBLISH WINGET PACKAGE
    - id: publish-winget-pkg
      name: Submit package to Windows Package Manager Community Repository
      if: startsWith(github.ref, 'refs/tags/')
      shell: powershell
      run: |
        # Submit package to Windows Package Manager Community Repository
        iwr https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
        .\wingetcreate.exe update schemacrawler.schemacrawler `
        --version 16.17.2 `
        --urls `
        https://github.com/schemacrawler/SchemaCrawler-Installers/releases/download/v16.17.2/SchemaCrawler-16.17.2.msi `
        --submit `
        --token ${{ secrets.WINGET_PUSH_TOKEN }}
